//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.08 at 04:43:35 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:demo:webservice:RequestEntity", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ms.student.entity;
