//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.08 at 04:43:35 PM IST 
//


package com.ms.student.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="StudentId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="StudentName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="English" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Science" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Maths" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "studentId",
    "studentName",
    "english",
    "science",
    "maths"
})
@XmlRootElement(name = "RequestEntity")
public class RequestEntity {

    @XmlElement(name = "StudentId", required = true)
    protected String studentId;
    @XmlElement(name = "StudentName", required = true)
    protected String studentName;
    @XmlElement(name = "English")
    protected int english;
    @XmlElement(name = "Science")
    protected int science;
    @XmlElement(name = "Maths")
    protected int maths;

    /**
     * Gets the value of the studentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * Sets the value of the studentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStudentId(String value) {
        this.studentId = value;
    }

    /**
     * Gets the value of the studentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * Sets the value of the studentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStudentName(String value) {
        this.studentName = value;
    }

    /**
     * Gets the value of the english property.
     * 
     */
    public int getEnglish() {
        return english;
    }

    /**
     * Sets the value of the english property.
     * 
     */
    public void setEnglish(int value) {
        this.english = value;
    }

    /**
     * Gets the value of the science property.
     * 
     */
    public int getScience() {
        return science;
    }

    /**
     * Sets the value of the science property.
     * 
     */
    public void setScience(int value) {
        this.science = value;
    }

    /**
     * Gets the value of the maths property.
     * 
     */
    public int getMaths() {
        return maths;
    }

    /**
     * Sets the value of the maths property.
     * 
     */
    public void setMaths(int value) {
        this.maths = value;
    }

}
